import Headtag from "@/components/headtag";

export default function Policy() {

  const meta = {
    title : "Privacy Policy - Stockverse",
    description : "Review the Privacy Policy of Stockverse. Learn about data collection, usage and your privacy rights while using our services and website",
    og_title : " ",
    og_description : " ",
    og_url : " ",
    og_img : " "
};

  return (
    <div className="hero py-16 max-md:py-6 w-full">
      <Headtag {...meta} />
      <div className="px-6 max-sm:px-3 mx-auto xl:container gap-y-4 max-sm:gap-y-3 flex flex-col items-start">
        <h1 className="text-3xl font-sansSemibold text-primaryText">Privacy Policy</h1>
        <p className="text-lg font-sansMedium text-primaryText">
          Last updated: November 18, 2024
        </p>
        <p className="text-base text-primaryText">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <p className="text-base text-primaryText">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. </p>
        <h2 className="mt-8 text-primaryText text-xl font-sansSemibold">1. Interpretation and Definitions</h2>
        <h2 className="mt-8 text-primaryText text-lg font-sansSemibold">Interpretation</h2>
        <p className="text-base text-primaryText">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        <h2 className="mt-8 text-primaryText text-lg font-sansSemibold">Definitions</h2>
        <p className="text-base text-primaryText">For the purposes of this Privacy Policy:</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Account</span>  means a unique account created for You to access our Service or parts of our Service.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where &#34;control&#34; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Company</span> (referred to as either &#34;the Company&#34;, &#34;We&#34;, &#34;Us&#34; or &#34;Our&#34; in this Agreement) refers to STOCKVERSE HOLDINGS LLC, 1309 COFFEEN AVE STE 1200 SHERIDAN, WY 82801.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Country</span> refers to: Ohio, United Statesp</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Personal</span> Data is any information that relates to an identified or identifiable individual.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Service</span> refers to the Website.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">Website</span> refers to Stockverse, accessible from <a className="text-primaryHeading" href='https://stockverse.com/'> https://stockverse.com/</a></p>
        <p className="text-base text-primaryText"><span className="font-sansSemibold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
        <h2 className="mt-8 text-primaryText text-xl font-sansSemibold">2. Collecting and Using Your Personal Data</h2>
        <h2 className="mt-8 text-primaryText text-lg font-sansSemibold">Types of Data Collected</h2>
        <p className="text-base text-primaryText font-sansSemibold">Personal Data</p>
        <p className="text-base text-primaryText">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ol className="list-disc pl-8 flex flex-col gap-y-4">
          <li className="text-base text-primaryText">Email address</li>
          <li className="text-base text-primaryText">First name and last name</li>
          <li className="text-base text-primaryText">Phone number</li>
          <li className="text-base text-primaryText">Usage Data</li>
        </ol>
        <p className="text-base text-primaryText font-sansSemibold">Usage Data</p>
        <p className="text-base text-primaryText">Usage Data is collected automatically when using the Service.</p>
        <p className="text-base text-primaryText">Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p className="text-base text-primaryText">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
        <p className="text-base text-primaryText">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
        <p className="text-base text-primaryText font-sansSemibold">Tracking Technologies and Cookies</p>
        <p className="text-base text-primaryText">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
        <ol className="list-disc pl-8 flex flex-col gap-y-4">
          <li className="text-base text-primaryText">Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
          <li className="text-base text-primaryText">Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ol>
        <p className="text-base text-primaryText">Cookies can be &#34;Persistent&#34; or &#34;Session&#34; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on <a className="text-primaryHeading" href="https://www.termsfeed.com/blog/cookies/"> TermsFeed website article.</a></p>
        <p className="text-base text-primaryText">We use both Session and Persistent Cookies for the purposes set out below:</p>
        <p className="text-base text-primaryText font-sansSemibold">Necessary / Essential Cookies</p>
        <p className="text-base text-primaryText">Type: Session Cookies</p>
        <p className="text-base text-primaryText">Administered by: Us</p>
        <p className="text-base text-primaryText">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
        <p className="text-base text-primaryText font-sansSemibold">Cookies Policy / Notice Acceptance Cookies</p>
        <p className="text-base text-primaryText">Type: Persistent Cookies</p>
        <p className="text-base text-primaryText">Administered by: Us</p>
        <p className="text-base text-primaryText">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
        <p className="text-base text-primaryText font-sansSemibold">Functionality Cookies</p>
        <p className="text-base text-primaryText">Type: Persistent Cookies</p>
        <p className="text-base text-primaryText">Administered by: Us</p>
        <p className="text-base text-primaryText">Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website</p>
        <p className="text-base text-primaryText">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
        <h2 className="mt-8 text-primaryText text-lg font-sansSemibold">Use of Your Personal Data</h2>
        <p className="text-base text-primaryText">The Company may use Personal Data for the following purposes</p>
        <ol className="list-disc pl-8 flex flex-col gap-y-4">
          <li className="text-base text-primaryText">To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li className="text-base text-primaryText">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li className="text-base text-primaryText">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
          <li className="text-base text-primaryText">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&#39;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li className="text-base text-primaryText">To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
          <li className="text-base text-primaryText">To manage Your requests: To attend and manage Your requests to Us.</li>
          <li className="text-base text-primaryText">For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
          <li className="text-base text-primaryText">For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
        </ol>
        <p className="text-base text-primaryText">We may share Your personal information in the following situations:</p>
        <ol className="list-disc pl-8 flex flex-col gap-y-4">
          <li className="text-base text-primaryText">With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
          </li>
          <li className="text-base text-primaryText">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li className="text-base text-primaryText">For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
          <li className="text-base text-primaryText">With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
          <li className="text-base text-primaryText">With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
          <li className="text-base text-primaryText">With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
          </li>
          <li className="text-base text-primaryText">With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>        
        </ol>
        <p className="text-base text-primaryText font-sansSemibold">Retention of Your Personal Data</p>
        <p className="text-base text-primaryText">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p className="text-base text-primaryText">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
        <p className="text-base text-primaryText font-sansSemibold">Transfer of Your Personal Data</p>
        <p className="text-base text-primaryText">Your information, including Personal Data, is processed at the Company&#39;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
        <p className="text-base text-primaryText">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
        <p className="text-base text-primaryText">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
        <p className="text-base text-primaryText font-sansSemibold">Delete Your Personal Data</p>
        <p className="text-base text-primaryText">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
        <p className="text-base text-primaryText">Our Service may give You the ability to delete certain information about You from within the Service.</p>
        <p className="text-base text-primaryText">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
        <p className="text-base text-primaryText">For information about deletion & removal of personal information, please see: <a className="text-primaryHeading" href="/guide/delete-account">Steps to Delete Your Stockverse Account</a></p>
        
        <p className="text-lg text-primaryText font-sansSemibold">Disclosure of Your Personal Data</p>
        <p className="text-base text-primaryText font-sansSemibold">Business Transactions</p>
        <p className="text-base text-primaryText">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
        <p className="text-lg text-primaryText font-sansSemibold">Law enforcement</p>
        <p className="text-base text-primaryText">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
        <p className="text-lg text-primaryText font-sansSemibold">Other legal requirements</p>
        <p className="text-base text-primaryText">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ol className="list-disc pl-8 flex flex-col gap-y-4">
          <li className="text-base text-primaryText">Comply with a legal obligation
          </li>
          <li className="text-base text-primaryText">Protect and defend the rights or property of the Company</li>
          <li className="text-base text-primaryText">Prevent or investigate possible wrongdoing in connection with the Service
          </li>
          <li className="text-base text-primaryText">Protect the personal safety of Users of the Service or the public
          </li>
          <li className="text-base text-primaryText">Protect against legal liability
          </li>        
        </ol>
        <p className="text-lg text-primaryText font-sansSemibold">Security of Your Personal Data</p>
        <p className="text-base text-primaryText">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        <p className="text-lg text-primaryText font-sansSemibold">Detailed Information on the Processing of Your Personal Data
        </p>
        <p className="text-base text-primaryText">The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
        <p className="text-lg text-primaryText font-sansSemibold">Analytics
        </p>
        <p className="text-base text-primaryText">We may use third-party Service providers to monitor and analyze the use of our Service.
        </p>
        <ol className="list-disc pl-8 flex flex-col gap-y-4">
          <li className="text-base text-primaryText">Google Analytics
          </li>      
        </ol>
        <p className="text-base text-primaryText">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
        </p>
        <p className="text-base text-primaryText">You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.
        </p>
        <p className="text-base text-primaryText">For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy" className="text-primaryHeading">https://policies.google.com/privacy</a>
        </p>
        <p className="text-lg text-primaryText font-sansSemibold">Email Marketing
        </p>
        <p className="text-base text-primaryText">We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.</p>
        <p className="text-lg text-primaryText font-sansSemibold">Payments
        </p>
        <p className="text-base text-primaryText">We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).
        </p>
        <p className="text-base text-primaryText">We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
        </p>
        <p className="text-lg text-primaryText font-sansSemibold">Mastercard
        </p>
        <p className="text-base text-primaryText">Their Privacy Policy can be viewed at
        </p>
        <a href="https://www.mastercard.us/en-us/vision/corp-responsibility/commitment-to-privacy/privacy.html" className="text-base text-primaryHeading">https://www.mastercard.us/en-us/vision/corp-responsibility/commitment-to-privacy/privacy.html
        </a>
        <p className="text-lg text-primaryText font-sansSemibold"> Visa
        </p>
        <p className="text-base text-primaryText"> Their Privacy Policy can be viewed at
        </p>
        <a href="https://www.visa.gp/legal/global-privacy-notice.html" className="text-base text-primaryHeading">https://www.visa.gp/legal/global-privacy-notice.html 
        </a>
        <p className="text-lg text-primaryText font-sansSemibold">  American Express
        </p>
        <p className="text-base text-primaryText">Their Privacy Policy can be viewed at 
        </p>
        <a href="https://www.americanexpress.com/us/company/privacy-center/online-privacy-disclosures/" className="text-base text-primaryHeading">https://www.americanexpress.com/us/company/privacy-center/online-privacy-disclosures/ 
        </a>
        <p className="text-lg text-primaryText font-sansSemibold"> Apple pay
        </p>
        <p className="text-base text-primaryText">Their Privacy Policy can be viewed at 
        </p>
        <a href="https://www.apple.com/legal/privacy/data/en/apple-pay/" className="text-base text-primaryHeading">https://www.apple.com/legal/privacy/data/en/apple-pay/ 
        </a>
        <p className="text-lg text-primaryText font-sansSemibold"> Google Pay
        </p>
        <p className="text-base text-primaryText">Their Privacy Policy can be viewed at 
        </p>
        <a href="https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&ldt=privacynotice&ldl=en-GB" className="text-base text-primaryHeading">https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&ldt=privacynotice&ldl=en-GB
        </a>
        <p className="text-lg text-primaryText font-sansSemibold"> Children&#39;s Privacy
        </p>
        <p className="text-lg text-primaryText">Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.
        </p>
        <p className="text-lg text-primaryText">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&#39;s consent before We collect and use that information.
        </p>
        <p className="text-lg text-primaryText font-sansSemibold">Links to Other Websites
        </p>
        <p className="text-lg text-primaryText">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&#39;s site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>
        <p className="text-lg text-primaryText">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
        <p className="text-lg text-primaryText font-sansSemibold">Changes to this Privacy Policy
        </p>
        <p className="text-lg text-primaryText">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="text-lg text-primaryText">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &#34;Last updated&#34; date at the top of this Privacy Policy.
        </p>
        <p className="text-lg text-primaryText">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
        <p className="text-lg text-primaryText font-sansSemibold">Contact Us
        </p>
        <p className="text-lg text-primaryText">If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <a href='mailto:support@stockverse.com' className="text-base text-primaryText"> By Email: <span className="text-primaryHeading">Support@stockverse.com</span></a>
      </div>
    </div>
  );
}